---
title: "Managing projects with R"
author: "Instructors: Daniel Falster & Will Cornwell"
date: "17/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Brief recap yesterday

- packages
- load data
- data_frames 
- Rmd files

## Project management (Dan, 9:30-11)

Live is complicated, and I used to be in pain, but now I live a blissfull peaceful happy existence with no worries aside from feeding unicorns.

### Exercises

Challenge - path names:

1. Download the course data (from Moodle or github)
2. Use the `dir` function to list contents of the folder

Challenge - projects:

1. Create an organized project directory for this stats course
2. Include an RStudio Project in the folder
3. Download the course data (from Moodle or github)
4. Create a file something like 'R_day1.R' 
5. Write one line of code to make a variable, and then save the object as a .rds file
6. When you finish put the green post-it on your laptop screen
7. Put up your green sticky when you're done
  - don't forget to use your directories (/data, /R, /output)
  
Optional:

Organize one of your own projects
  
# Reproducible research with Rmarkdown