

## General R & Rstudio

- Rstudio learning materials: https://education.rstudio.com/learn/
	- cheatsheets: https://www.rstudio.com/resources/cheatsheets/
	- books: https://rstudio.com/resources/books/
	- Beginner tutorials: https://education.rstudio.com/learn/beginner/
	- tutorials: https://rstudio.cloud/learn/primers
- 3 useful shortcuts: http://jenrichmond.rbind.io/post/hotkeys/ and the full list https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts

## Material from our website Environmentalcomputing.net

- http://environmentalcomputing.net/installing-r-r-studio/
- http://environmentalcomputing.net/importing-data/
- http://environmentalcomputing.net/data-types-and-structure/
- http://environmentalcomputing.net/making-new-variables/
- http://environmentalcomputing.net/subsetting-data/
- http://environmentalcomputing.net/basic-project-management/

## Cool books

* R for data science, https://r4ds.had.co.nz
* Art of data science, https://bookdown.org/rdpeng/artofdatascience/)
* Claus Wilke's Fundamentals of Data Visualization, https://serialmentor.com/dataviz/index.html)
* Winston Chang's R Graphics Cookbook, https://r-graphics.org

## Data manipulation

- [Data manipulation on environmentalcomputing.net](http://environmentalcomputing.net/data-manipulation/)
- [Datacarpentry's lesson on data manipulation](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html)
- [The `tidylog` package](https://github.com/elbersb/tidylog) is cool for understanding what happens with dplyr operations

## Data visualisation

ggplot:

* ggplot: https://ggplot2.tidyverse.org/index.html
* collection of examples and methods: https://www.datanovia.com/en/blog/ggplot-examples-best-reference/
* ggplot themes: https://ggplot2.tidyverse.org/reference/ggtheme.html
* ggplot homepage: https://ggplot2.tidyverse.org
* Plotting with ggplot on environmentalcomputing.net: http://environmentalcomputing.net/plotting-with-ggplot/
* Visualising data with ggplot from Data Carpentry: https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html
* Recommended ggplot extensions: http://www.ggplot2-exts.org/gallery/

general:

* From Data to viz: https://www.data-to-viz.com/, a great website over-viewing different kinds of graphic
* The data visualisation (http://r4ds.had.co.nz/data-visualisation.html) and graphics for communication (http://r4ds.had.co.nz/graphics-for-communication.html) chapters of Hadley Wickham;s R for data science.

## Rmarkdown

You can use Rmd files to create all sorts of stuff:

- html files (including websites)
- word documents
- pdf (maybe)
- blogs (see package blogdown)

Guides:

- Rmarkdown, the definitive guide: https://bookdown.org/yihui/rmarkdown/
- knitr, https://yihui.org/knitr/
- Pimp my Rmd: https://holtzy.github.io/Pimp-my-rmd/


## Open Datasets to play with

- [Tidy Tuesday](https://www.tidytuesday.com)

