---
title: "ggplot2"
author: "Fonti Kar"
date: "20/09/2018"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

##Slide 6 - An example 

```{r s6, echo=T, warning = F, message = F}
library(ggplot2)

ggplot(iris, aes(x = Species, y = Petal.Length)) + geom_boxplot() + theme_bw()
```

##Slide 7, 8 - Some other key plots

```{r s7and8, echo=T, warning = F, message = F}
ggplot(iris, aes(x = Petal.Length)) + geom_histogram() + theme_bw()
ggplot(iris, aes(x = Petal.Length, y = Petal.Width)) + geom_point() + theme_bw()
```

##Slide 11 - 14 Data wrangling and barplots with base and ggplot2

```{r s11_14, echo = T, warning = F, message = F}
library(dplyr)

iris.barplot <- iris %>% group_by(Species) %>% summarise(meanPetal.Length = mean(Petal.Length), stderPetal.Length = sd(Petal.Length)/sqrt(length(Petal.Length)), lowerErr = (meanPetal.Length - stderPetal.Length), upperErr = (meanPetal.Length + stderPetal.Length))

iris.barplot
          
ggplot(iris.barplot, aes(x = Species, y = meanPetal.Length)) + geom_col(width = 0.5) + geom_errorbar(aes(ymin = lowerErr, ymax = upperErr), width = 0.1) + theme_bw() 

#Base R 
meanPetal.length <- tapply(iris$Petal.Length, iris$Species, mean)
nPetal.length <- tapply(iris$Petal.Length, iris$Species, length)
sePetal.length <- tapply(iris$Petal.Length, iris$Species,sd)/sqrt(nPetal.length) 

xx <- barplot(meanPetal.length,ylim=c(0,max(meanPetal.length+sePetal.length)*1.1)) 
#we add error bars using the function arrows()
#by setting code=3, we get arrow heads on both ends
#by setting angle=90, the arrow heads become flat
arrows(xx,meanPetal.length-sePetal.length,xx,meanPetal.length+sePetal.length, angle=90,code=3, length = 0.1)
#adds box to outside of figure
box()
```

##Slide 16 Themes

```{r s16_themes, echo =T, warning = F, message = F}
irisboxplot <- ggplot(iris, aes(x = Species, y = Petal.Length)) + geom_boxplot()

irisboxplot + theme_classic() 

irisboxplot + theme_gray() 

irisboxplot + theme_light() 

irisboxplot + theme_minimal() 

irisboxplot + theme_void() 
```

##Slide 17 - 19 Customising your plot but less is more! 

```{r s17_19, echo =T, warning = F, message = F}
ggplot(data = iris, aes(x = Petal.Width, y = Petal.Length, color = Species)) + geom_point(size = 2.5, alpha = 0.6) +
  theme_bw() +  theme(legend.position = "bottom",
                      legend.text = element_text(size = 12, family="Comic Sans MS"),
                      legend.title = element_text(size = 12, face = "bold" , family= "Comic Sans MS"), panel.grid.major = element_blank(),
                      panel.grid.minor = element_blank(),axis.text= element_text(size = 18), 
                      axis.title= element_text(size = 20,face = "bold", family="Comic Sans MS"))

ggplot(data = iris, aes(x = Petal.Width, y = Petal.Length, shape = Species)) + geom_point() +
  theme_bw() 
```          

##Slide 20 -21 Facets
                 
```{r s20_21, echo =T, warning = F, message = F}
Toothplot <- ggplot(data = ToothGrowth, aes(x = factor(dose), y = len)) + 
  geom_boxplot() + 
  theme_bw() 

Toothplot + facet_wrap(~supp)

ToothGrowth$Sex <- rep(c("F", "M"), 2, 30) #Creating some fake sex data

ggplot(data = ToothGrowth, aes(x = factor(dose), y = len)) + 
  geom_boxplot() + 
  facet_grid(Sex ~supp) + 
  theme_bw() 
```          

##Slide 22 - 23 Built in functions
                           
```{r s22_23, echo =T, warning = F, message = F}
ggplot(data = ToothGrowth, 
aes(x = factor(dose), y = len, fill = dose)) +
  geom_violin(trim = F) + 
  geom_point(col = "white", size = 2, alpha = 0.2) + 
  stat_summary(fun.data = "mean_se", col = "white") + 
  theme_bw() 

 ggplot(data = iris, aes(x = Petal.Width, y = Petal.Length)) + 
   geom_point(aes(color = Species),size = 5, alpha = 0.3) + 
   geom_line(stat="smooth", method = "lm", alpha = 0.3) +  
   geom_line(aes(group = Species, colour = Species), stat="smooth", method = "lm", lwd = 0.5) +
   theme_bw() 
```           

##Slide 26 -27 Working with palettes

```{r s24_25_cols, echo = T, warning = F, message = F}
library(viridis)

irisplot <- ggplot(data = iris, aes(x = Petal.Width, y = Petal.Length, color = Species)) + 
  geom_point(size = 5) + 
  theme_bw() 

irisplot  + scale_color_viridis(discrete = T)

irisplot  + scale_color_viridis(discrete = T, option = "B")
  
irisplot  + scale_color_viridis(discrete = T, option = "C")
```

```{r 26_27_cols, echo = T, warning = F, message = F}
devtools::install_github("karthik/wesanderson")
library(wesanderson)

toothplot <- ggplot(data = ToothGrowth, aes(x = factor(dose), y = len, fill = factor(dose))) + 
  geom_violin(trim = F) + 
  geom_point(col = "white", size = 2, alpha = 0.2) + 
  stat_summary(fun.data = "mean_se", col = "white") + 
  theme_bw() 

toothplot + scale_fill_manual(values = wes_palette("IsleofDogs1"))
toothplot + scale_fill_manual(values = wes_palette("FantasticFox1"))
toothplot + scale_fill_manual(values = wes_palette("Cavalcanti1"))
```

