---
title: "Data Manipulation and Visualization"
author: "Instructors: Daniel Falster & Will Cornwell"
date: "17/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction to data manipulation with `dplyr` intro

(Will, 11:15 - 12:15)

## Motivation

Data is never organized in the way you want it 

High % of project is data wrangling

Many many many modern jobs are data wrangling

## Key ideas

Data is a noun

Actions on data are verbs  

Learn a few key verbs and what they do

read_csv

filter

select

mutate

arrange

distinct


group_by

summarise

count 

n

rename

the `join` family

Pipes

- use the operator `%>%` 
- If you use RStudio, you can type the pipe with Ctrl + Shift + M if you have a PC or Cmd + Shift + M if you have a Mac.

**Exercises:**

**Resources:**

- [Data manipulation on environmentalcomputing.net](http://environmentalcomputing.net/data-manipulation/) 
- [Datacarpentry's lesson on data manipulation](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html)
- [The `tidylog` package](https://github.com/elbersb/tidylog) is cool for understanding what happens with dplyr operations

# Lunch

(12:30-13:30)


# Data Wrangling

(13:30-14:00)

**Exercises:** Apply the `dplyr` package and your new data wrangling skills to the sydney beaches dataset to 

1. Create a subset of the dataset consisting of only records taken since 2016
2. As above and only variables `Site`, `Latitude`, and `Longitude`
3. As above but with only one record per Site
3. As above but with data sorted by `Latitude`
4. For each Site, calculate the number of records, the min, mean, median and max value of `Enterococci_cfu_per_100ml` 
5. For each record, create a new variable giving the year the record was collected (hint: the package lubridate could be helpful, see the cheatsheet) 

# Data Visualisation

(14:00-15:00)

## ggplot philosophy and intro

Fonti Kar is coming to give  a session on ggplot philosophy 

**Exercises:** In pairs, discuss a hypothesis you can address using the Sydney Beaches dataset and the plot you would like to make to demonstrate this. Try to make the plot using ggplot. In making your plot consider

- what goes on the x & y axes?
- is it one panel or many panels?
- what type of plot would be best?
- what aesthetics are you going to use: i.e. symbols, colours, etc?
- should axes be log scaled?
- is there anything else about the plot style you would change if you could?
- try saving the plot as a png and pdf using the function `ggsave`


## Extra things to consider / discuss

- ggplot vs base R graphics: 
- themes
- special axes (log)
- facets
- colours, symbols
- types of plots (incl extra packages, ggbeeswarm)
- ggsave
- ?patchwork (load via source install)
- stats: gmsmooth, lm
- plotly

**Resources:**

Some resources for using ggplot:

* [ggplot homepage](https://ggplot2.tidyverse.org)
* [Plotting with ggplot on environmentalcomputing.net](http://environmentalcomputing.net/plotting-with-ggplot/)
* [Visualising data with ggplot from Data Carpentry](https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html)
* [Recommended ggplot extensions](http://www.ggplot2-exts.org/gallery/)
* The [data visualisation](http://r4ds.had.co.nz/data-visualisation.html) and [graphics for communication](http://r4ds.had.co.nz/graphics-for-communication.html) chapters of Hadley Wickham;s R for data science.

Some general resources on data visualisation:

* [Claus O. Wilke's book Fundamentals of Data Visualization](https://serialmentor.com/dataviz/index.html)
* [From Data to viz](https://www.data-to-viz.com/), a great website over-viewing different kinds of graphic
* [R Graphics Cookbook  by Winston Chang](https://www.amazon.com/dp/1449316956/ref=as_li_ss_tl?&linkId=4daa45d4fbd0a187163a6ff9d56d986e)



