---
title: "Introduction to R"
author: "Instructors: Daniel Falster & Will Cornwell"
date: "17/12/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Welcome

(Dan, 9:00-9:30)

Logistics

- nametags: sticker and desk
- post it  notes, 

Getting to know you:

- who has used R
- best & worst experience, worries, why here

Aims of this course:

- Introduction to R & Rstudio
- Getting data in and out of R 
- R objects and classes
- Packages
- Data manipulation
- Data visualisation

# A quick demo of some things you can do

(Dan, 9:30-10:00)

What is R

- Code vs console vs Rmd
- differnt clients

Demonstration of data analysis -- using the Sydney Beaches dataset

Interesting links:

- How much R is used in Ecology: https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecs2.2567
- https://www.tidyverse.org/
- R4DS: https://r4ds.had.co.nz/


#  The Rstudio environment 

(Will, 10:00-10:30)

Rstudio 

- into to panels panels

Writing code

- Code vs console vs Rmd
- Rmarkdown (code chunks, markdown)

Packages

- installing
- tidyverse
- loading


**Exercise:** Install R (>3.5), Rstudio (1.1.463), and the `tidyverse` packages

# Doing a full analysis yourself

(Will, 10:30-11:00)

**Exercise:** Download course materials and knit demo. Make sure they can knit the demo. Take time to fix any issues that arise.
  
# Morning tea

(11:00-11:30)

# Assigning objects

(Dan, 11:30-12:00)

- Code vs console vs Rmd
- <- 
- making variables
- Rstudio environment panel
- errors
- -> (works more naturally)
- = 

**Exercise:**

- make new variables containing a character and numeric content 
- load the XXX dataset and assign to variable name

# Loading data

(Dan, 12:00-12:30)

- file types
- loading other file types
  - include examples but not discuss much 
  - excel, googlesheets, web csv
- loading csv files
  - base vs readr
  - headers

**Exercise:**

- readxl: https://readxl.tidyverse.org/reference/read_excel.html
- datapasta: https://cran.r-project.org/web/packages/datapasta/
- googlesheets4: https://googlesheets4.tidyverse.org/


# Lunch 

(12:30 - 13:30)

# Object types I

(Will, 13:30-14:30)

- data frame
   - columns
   - $
- vector
   - []
   - :

**Exercise:**

- data types
  - character
  - integer
  - numeric
  - boolean
  - dates
- variables
- matrix
- lists
  - non-table structures
  - calling via names, numbers

# Useful Vocabulary for exploring data

(Dan, 14:30-15:00)

- vector
  - numeric: mean, max, length
  - character: unique

1. load data, 
  - take column, first 5 values, take mean
  - take all column x by value column y, first 5 values, take mean
  - multiply columns together
  - multiply columns together then sum
2. (for some data) Calculate sd and check against sd function

# Afternoon tea

(15:00 - 15:30)

# Exploring data

**Exercise:**

# More complicated functions and how to use them 

(Dan. 16:00-16:30)

- arguments for functions
- default values
- = 
- outputs of functions
- lm
- formula

**Exercise:**

# Optional extras

- getting help
  - google
  - about functions
- more on Rmd
- generating data
  - distributions

