---
title: "Introduction to R"
author: "Instructors: Daniel Falster & Will Cornwell"
date: "17/12/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Aims

Getting started with R

- Introduction to Rstudio
- Introduction to coding in R
- Getting data in and out of R 
- R objects and classes
- Packages

# Welcome (Dan, 30 min)

- housekeep, post its, nametags
- warm up: 
 - who has used R
 - best & worst experience, worries, why here
- overview

# Intro demo (Dan, 30 min)

- brief intro Rstudio
- demo  

#  The Rstudio environment  (Will, 30 min)



- code / scripts / Rmarkdown

Packages

- installing
- tidyverse
- loading

- Exercise: Install R (>3.5), Rstudio (1.1.463), and tidyverse

# Doing a full analysis yourself (Will, 30 min)

- Exercise: Download course materials and knit demo 

- fix issues
  
# Morning tea 11 AM

# Assigning 11 - 1130 (Dan)

- <- 
- making variables
- Rstudio environment panel
- errors
- -> (works more naturally)
- = 

Exercise:

- make new variables containing a character and numeric content 
- load the XXX dataset and assign to variable name

# Loading data 11:30 - 12 (Dan)

- file types
- loading other file types
  - include examples but not discuss much 
  - excel, googlesheets, web csv
- loading csv files
  - base vs readr
  - headers

Exercise:

# Object types I (Will 12-12:30)

- data frame
   - columns
   - $
- vector
   - []
   - :

exercise:

# Lunch 12:30 - 13:30

# Object types II (Will 13:30-14:00)

- data types
  - character
  - integer
  - numeric
  - boolean
  - dates
- variables
- matrix
- lists
  - non-table structures
  - calling via names, numbers

# Useful Vocabulary for exploring data (Dan, 14-15)

- vector
  - numeric: mean, max, length
  - character: unique

1. load data, 
  - take column, first 5 values, take mean
  - take all column x by value column y, first 5 values, take mean
  - multiply columns together
  - multiply columns together then sum
2. (for some data) Calculate sd and check against sd function

# AFTERNOON TEA (15 - 1530)

# More complicated functions and how to use them(Dan 1530-1600)

- arguments for functions
- default values
- = 
- outputs of functions
- lm
- formula



Exercises





# Optional extras

- getting help
  - google
  - about functions
- more on Rmd
- generating data
  - distributions

