

## Data manaipulation


**Resources:**

- [Data manipulation on environmentalcomputing.net](http://environmentalcomputing.net/data-manipulation/) 
- [Datacarpentry's lesson on data manipulation](https://datacarpentry.org/R-ecology-lesson/03-dplyr.html)
- [The `tidylog` package](https://github.com/elbersb/tidylog) is cool for understanding what happens with dplyr operations


## Data visualisation

**Resources:**

Some resources for using ggplot:

* [ggplot homepage](https://ggplot2.tidyverse.org)
* [Plotting with ggplot on environmentalcomputing.net](http://environmentalcomputing.net/plotting-with-ggplot/)
* [Visualising data with ggplot from Data Carpentry](https://datacarpentry.org/R-ecology-lesson/04-visualization-ggplot2.html)
* [Recommended ggplot extensions](http://www.ggplot2-exts.org/gallery/)
* The [data visualisation](http://r4ds.had.co.nz/data-visualisation.html) and [graphics for communication](http://r4ds.had.co.nz/graphics-for-communication.html) chapters of Hadley Wickham;s R for data science.

Some general resources on data visualisation:

* [Claus O. Wilke's book Fundamentals of Data Visualization](https://serialmentor.com/dataviz/index.html)
* [From Data to viz](https://www.data-to-viz.com/), a great website over-viewing different kinds of graphic
* [R Graphics Cookbook  by Winston Chang](https://www.amazon.com/dp/1449316956/ref=as_li_ss_tl?&linkId=4daa45d4fbd0a187163a6ff9d56d986e)

## Reproducible research


